language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

before_script:
    - pip install -e ".[test]"
    - pip install coveralls

script:
    - py.test --pep8 --cov appfigures --cov-report term-missing

after_success:
    - coveralls
