language: python

env:
    matrix:
        - TOX_ENV=py27
    allow_failures:
        - TOX_ENV=py34

before_script:
    - pip install tox coveralls

script:
    - tox -e ${TOX_ENV}

after_success:
    - coveralls
